name: air-quality-mdn
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pandas=2.2.2
  - pytorch=2.6.0
  - torchvision  # Optional, but often needed with torch
  - optuna=4.3.0
  - matplotlib=3.10.0
  - scipy=1.12.0
  - tqdm=4.67.1
  - imageio=2.36.1
  - pillow=11.0.0
  - pip
  - pip:
      - torch==2.6.0+cu126  # Ensure CUDA version is specified if using pip torch wheel